create schema if not exists private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null,
  role text not null default 'member' check (role in ('admin', 'member')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('insert', 'update', 'delete')),
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_created_at_idx on public.activity_logs(created_at desc);
create index if not exists activity_logs_user_id_idx on public.activity_logs(user_id);

alter table public.profiles enable row level security;
alter table public.activity_logs enable row level security;

revoke all on public.clients from anon;
revoke all on public.tasks from anon;
revoke all on public.invoices from anon;
revoke all on public.profiles from anon;
revoke all on public.activity_logs from anon;

grant select on public.clients to authenticated;
grant insert, update, delete on public.clients to authenticated;
grant select, insert, update, delete on public.tasks to authenticated;
grant select, insert, update, delete on public.invoices to authenticated;
grant select on public.profiles to authenticated;
grant select on public.activity_logs to authenticated;
grant usage, select on sequence public.activity_logs_id_seq to authenticated;

drop policy if exists "temporary public clients access" on public.clients;
drop policy if exists "temporary public tasks access" on public.tasks;
drop policy if exists "temporary public invoices access" on public.invoices;

create policy "authenticated users can read clients"
on public.clients for select to authenticated using (true);
create policy "admins can create clients"
on public.clients for insert to authenticated
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins can update clients"
on public.clients for update to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins can delete clients"
on public.clients for delete to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "team can read tasks"
on public.tasks for select to authenticated using (true);
create policy "team can create tasks"
on public.tasks for insert to authenticated with check (true);
create policy "team can update tasks"
on public.tasks for update to authenticated using (true) with check (true);
create policy "team can delete tasks"
on public.tasks for delete to authenticated using (true);

create policy "admins can read invoices"
on public.invoices for select to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins can create invoices"
on public.invoices for insert to authenticated
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins can update invoices"
on public.invoices for update to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins can delete invoices"
on public.invoices for delete to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "team can read profiles"
on public.profiles for select to authenticated using (true);
create policy "team can read activity"
on public.activity_logs for select to authenticated using (true);

drop policy if exists "temporary public billing select" on storage.objects;
drop policy if exists "temporary public billing insert" on storage.objects;
drop policy if exists "temporary public billing update" on storage.objects;
drop policy if exists "temporary public billing delete" on storage.objects;

create policy "authenticated users can read billing documents"
on storage.objects for select to authenticated
using (bucket_id = 'billing-documents');
create policy "admins can upload billing documents"
on storage.objects for insert to authenticated
with check (bucket_id = 'billing-documents' and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins can update billing documents"
on storage.objects for update to authenticated
using (bucket_id = 'billing-documents' and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check (bucket_id = 'billing-documents' and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins can delete billing documents"
on storage.objects for delete to authenticated
using (bucket_id = 'billing-documents' and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create or replace function private.log_crm_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  record_id text;
begin
  if tg_op = 'UPDATE'
    and (to_jsonb(new) - 'updated_at' - 'created_at') is not distinct from (to_jsonb(old) - 'updated_at' - 'created_at')
  then
    return new;
  end if;

  record_id := coalesce(to_jsonb(new) ->> 'id', to_jsonb(old) ->> 'id');
  insert into public.activity_logs (user_id, action, entity_type, entity_id)
  values (auth.uid(), lower(tg_op), tg_table_name, record_id);
  return coalesce(new, old);
end;
$$;

revoke all on function private.log_crm_activity() from public, anon, authenticated;

drop trigger if exists log_clients_activity on public.clients;
create trigger log_clients_activity after insert or update or delete on public.clients
for each row execute function private.log_crm_activity();
drop trigger if exists log_tasks_activity on public.tasks;
create trigger log_tasks_activity after insert or update or delete on public.tasks
for each row execute function private.log_crm_activity();
drop trigger if exists log_invoices_activity on public.invoices;
create trigger log_invoices_activity after insert or update or delete on public.invoices
for each row execute function private.log_crm_activity();

insert into public.profiles (id, email, full_name, role)
select
  id,
  email,
  coalesce(raw_user_meta_data ->> 'display_name', raw_user_meta_data ->> 'name', split_part(email, '@', 1)),
  case when lower(email) = 'wil@swira.es' then 'admin' else 'member' end
from auth.users
where lower(email) in ('christian@swira.es', 'wil@swira.es', 'rafa@swira.es')
on conflict (id) do update set
  email = excluded.email,
  full_name = excluded.full_name,
  role = excluded.role,
  updated_at = now();
